In [1]:
# Import libaraies and helper functions

import pandas as pd 
import os
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor
from datetime import datetime
from sklearn.preprocessing import StandardScaler
from sklearn import decomposition
import yellowbrick as yb
from yellowbrick.features import Rank1D
from yellowbrick.features import Rank2D
import warnings

In [2]:
# load the weather and  electricity data 
meter_data1=pd.read_csv("homeA2014.csv",parse_dates=True,index_col='Date & Time')
Meter_data2=pd.read_csv("HomeA-meter2_2014.csv",parse_dates=True,index_col='Date & Time')
Meter_data3=pd.read_csv("HomeA-meter3_2014.csv",parse_dates=True,index_col='Date & Time')
Meter_data4=pd.read_csv("HomeA-meter4_2014.csv",parse_dates=True,index_col='Date & Time')

In [3]:
#load the first meter data  rows
meter_data1.head()

,temperature,icon,humidity,visibility,summary,apparentTemperature,pressure,windSpeed,cloudCover,windBearing,precipIntensity,dewPoint,precipProbability
Date & Time,,,,,,,,,,,,,
2014-01-01 00:00:00,16.67,clear-night,0.53,10.0,Clear,3.95,1022.69,11.23,0.00,271.0,0.0,2.41,0.0
2014-01-01 01:00:00,16.19,clear-night,0.52,10.0,Clear,4.18,1022.58,9.92,0.02,268.0,0.0,1.68,0.0
2014-01-01 02:00:00,15.69,clear-night,0.55,10.0,Clear,4.41,1023.61,8.72,0.00,266.0,0.0,2.59,0.0
2014-01-01 03:00:00,15.29,clear-night,0.58,10.0,Clear,4.29,1024.31,8.25,0.00,269.0,0.0,3.29,0.0
2014-01-01 04:00:00,15.37,clear-night,0.60,10.0,Clear,5.12,1024.51,7.38,0.06,266.0,0.0,3.95,0.0

In [4]:
Meter_data2.head()

,use [kW],gen [kW],FurnaceHRV [kW],CellarOutlets [kW],WashingMachine [kW],FridgeRange [kW],DisposalDishwasher [kW],KitchenLights [kW],BedroomOutlets [kW],BedroomLights [kW],MasterOutlets [kW],MasterLights [kW],DuctHeaterHRV [kW]
Date & Time,,,,,,,,,,,,,
2014-01-01 00:00:00,0,0,0.195338,0.083204,0.005686,0.006892,0.005569,0.012154,0.020452,0.004899,0.046563,0.010393,0.382682
2014-01-01 00:30:00,0,0,0.182158,0.036139,0.005679,0.094138,0.005412,0.005200,0.020571,0.008869,0.051677,0.009884,0.275576
2014-01-01 01:00:00,0,0,0.134808,0.047034,0.005635,0.014786,0.005510,0.003173,0.020516,0.004901,0.053619,0.010183,0.346067
2014-01-01 01:30:00,0,0,0.182125,0.071407,0.005672,0.082081,0.005445,0.003072,0.020506,0.004844,0.050543,0.009996,0.310117
2014-01-01 02:00:00,0,0,0.092988,0.014203,0.005570,0.031901,0.005401,0.003154,0.020412,0.004841,0.049052,0.009927,0.309781

In [5]:
Meter_data3.head()

,use [kW],gen [kW],ElectricRange [kW],Dryer [kW],GarageMudroomLights [kW],DiningRoomOutlets [kW],MudroomOutlets [kW],MasterBathOutlets [kW],GarageOutlets [kW],BasementOutdoorOutlets [kW]
Date & Time,,,,,,,,,,
2014-01-01 00:00:00,0,0,0.002883,0.005231,0.013155,0,0,0,0,0
2014-01-01 00:30:00,0,0,0.003022,0.005441,0.012962,0,0,0,0,0
2014-01-01 01:00:00,0,0,0.002979,0.005293,0.013107,0,0,0,0,0
2014-01-01 01:30:00,0,0,0.002955,0.005317,0.012978,0,0,0,0,0
2014-01-01 02:00:00,0,0,0.003059,0.005368,0.012886,0,0,0,0,0

In [6]:
Meter_data4.head()

,use [kW],gen [kW],KitchenDenLights [kW],MasterBedBathLights [kW],MasterOutlets [kW],DenOutdoorLights [kW],DenOutlets [kW],RearBasementLights [kW],KitchenOutletsEast [kW],KitchenOutletsSouth [kW],DishwasherDisposalSinkLight [kW],Refrigerator [kW],Microwave [kW],OfficeLights [kW]
Date & Time,,,,,,,,,,,,,,
2014-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-01-01 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-01-01 00:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-01-01 00:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2014-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
plt.figure(figsize=(10,20))
    plt.figure()
    df.iloc[:,i].plot()
    plt.title(df.columns[i])
plt.tight_layout